services:
  web:
    container_name: web
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/:/home/web/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    volumes:
      - dev:/var/lib/postgresql/data/
    ports:
      - ${SQL_PORT}:${SQL_PORT}
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    env_file:
      - .env

volumes:
  dev:
