services:
  web:
    container_name: web
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/home/web/app/staticfiles
      - media_volume:/home/web/app/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    volumes:
      - prod:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

  nginx:
    container_name: server
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/web/app/staticfiles
      - media_volume:/home/web/app/media
    ports:
      - "443:433"
      - "80:80"
    depends_on:
      - web

  backup:
    container_name: backup
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    volumes:
      - backup:/backups
    links:
      - db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=${SQL_HOST}
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6

volumes:
  prod:
  static_volume:
  media_volume:
  backup: