version: "3.3"
services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: 'meu_site'
      MYSQL_USER: 'enzos'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'

  python:
    image: python:3.8
    container_name: python_interpreter
    working_dir: /usr/src/meu_site
    tty: true
    stdin_open: true
    command: python3

  web:
    build: .
    container_name: meu_site
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - python