# Generated by Django 5.1.7 on 2025-03-18 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subtítulo')),
                ('text', models.TextField(verbose_name='Texto')),
                ('language_code', models.CharField(choices=[('pt-br', 'Português'), ('en', 'English')], max_length=5, verbose_name='Código de Linguagem')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='Postagem')),
            ],
            options={
                'verbose_name': 'Versão',
                'verbose_name_plural': 'Versões',
                'unique_together': {('post', 'language_code')},
            },
        ),
    ]
