# Generated by Django 3.2.5 on 2021-07-28 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 17, 21, 8, 512470), verbose_name='Data de publicação'),
        ),
    ]
