# Generated by Django 3.2.5 on 2021-07-28 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 18, 29, 23, 551412), verbose_name='Data de publicação'),
        ),
    ]
