# Generated by Django 3.2.5 on 2021-07-28 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 19, 33, 5, 174296), verbose_name='Data de publicação'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
