# Generated by Django 3.2.5 on 2021-07-28 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210728_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 19, 34, 46, 376442), verbose_name='Data de publicação'),
        ),
    ]
