# Generated by Django 3.2.5 on 2021-07-30 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 30, 0, 25, 15, 574771), verbose_name='Data de publicação'),
        ),
    ]
