# Generated by Django 3.2.5 on 2021-07-30 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 30, 1, 42, 24, 489650), verbose_name='Data de publicação'),
        ),
    ]
