# Generated by Django 3.2.6 on 2021-08-09 03:33

import authentication.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(authentication.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(default='Uma descrição sobre mim', null=True, verbose_name='Sobre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='Número de telefone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cv',
            field=models.FileField(null=True, upload_to='', verbose_name='Currículo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ddd',
            field=models.CharField(default='', max_length=2, null=True, verbose_name='DDD'),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Foto'),
        ),
    ]
