# Generated by Django 3.2.5 on 2021-07-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210729_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ddd',
            field=models.CharField(max_length=2, verbose_name='DDD'),
        ),
    ]
