# Generated by Django 3.2.6 on 2021-08-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_ddd'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(default='temp', verbose_name='Sobre'),
            preserve_default=False,
        ),
    ]
