# Generated by Django 3.2.6 on 2021-08-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0005_alter_experience_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(default=None, null=True, verbose_name='Data de desligamento'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default=None, verbose_name='Data de começo'),
        ),
    ]
