# Generated by Django 3.2.6 on 2021-08-06 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210805_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='post',
        ),
    ]
