# Generated by Django 3.2.6 on 2021-08-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.CharField(default='https://www.facebook.com/enzo.soutosoares/', max_length=50),
            preserve_default=False,
        ),
    ]
