# Generated by Django 3.2.6 on 2021-08-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0006_auto_20210813_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data de desligamento'),
        ),
    ]
