# Generated by Django 3.2.6 on 2021-08-14 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0009_delete_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome da instituição')),
                ('start_date', models.DateField(default=None, verbose_name='Data de começo')),
                (
                'end_date', models.DateField(blank=True, default=None, null=True, verbose_name='Data de desligamento')),
                ('position', models.CharField(max_length=20, verbose_name='Cargo')),
                ('place', models.CharField(max_length=30, verbose_name='Localidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
