# Generated by Django 3.2.6 on 2021-08-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome da instituição'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome da empresa'),
        ),
    ]
