# Generated by Django 3.2.6 on 2021-08-14 02:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0011_auto_20210813_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='position',
        ),
    ]
