# Generated by Django 3.2.6 on 2021-08-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0013_auto_20210813_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Nome'),
        ),
    ]
