# Generated by Django 3.2.6 on 2021-08-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(null=True, verbose_name='Link'),
        ),
    ]
