# Generated by Django 3.2.6 on 2021-08-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20210814_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Descrição'),
        ),
    ]
